name: Code Style Check

on:
  push:
    branches:
      - structure_change
  pull_request:
    branches:
      - structure_change

jobs:
  lint:
    name: Check Code Style with Black
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Black
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      # Step 4: Run Black to check formatting
      - name: Run Black
        run: black --check --diff . --verbose